{"name": "test_invalidLogin", "status": "failed", "statusDetails": {"message": "AssertionError: assert False == True", "trace": "self = <tests.home.test_login.LoginTests testMethod=test_invalidLogin>\n\n    @pytest.mark.run(order=1)\n    def test_invalidLogin(self):\n        self.lp.login(\"test@email.com\", \"abcabcabc\")\n        result = self.lp.verifyLoginFailed()\n>       assert result == True\nE       AssertionError: assert False == True\n\ntest_login.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "e001eb55-3647-450e-b67a-70f0af0a48a5-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "70a96e63-f5bf-4c2c-b408-025b582f80f9-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "05328145-f62a-4b1e-90e7-f4b75dadbebf-attachment.txt", "type": "text/plain"}], "start": 1599032405305, "stop": 1599032420596, "uuid": "09d3c86f-9369-4314-ad08-5da6b341e361", "historyId": "bd0cb39fb65b17993d6dc066ecec2e03", "testCaseId": "2af3620ad13010691d049ff6e2ce1e4c", "fullName": "test_login.LoginTests#test_invalidLogin", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('oneTimeSetUp', 'setUp')"}, {"name": "tag", "value": "run(order=1)"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "LoginTests"}, {"name": "host", "value": "DESKTOP-1LDCU8B"}, {"name": "thread", "value": "14388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}