{
  "uid" : "b4694d1406f7151",
  "name" : "test_validLogin",
  "fullName" : "tests.home.test_login.LoginTests#test_validLogin",
  "historyId" : "80c51dfd5f134294812b6d779e500661",
  "time" : {
    "start" : 1599032695427,
    "stop" : 1599032707762,
    "duration" : 12335
  },
  "status" : "failed",
  "statusMessage" : "AssertionError",
  "statusTrace" : "self = <tests.home.test_login.LoginTests testMethod=test_validLogin>\n\n    @pytest.mark.run(order=2)\n    def test_validLogin(self):\n        self.lp.login(\"test@email.com\", \"abcabc\")\n        result1 = self.lp.verifyLoginTitle()\n        self.ts.mark(result1, \"Title Verification\")\n        result2 = self.lp.verifyLoginSuccessful()\n>       self.ts.markFinal(\"test_validLogin\", result2, \"Login Verification\")\n\ntest_login.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilities.teststatus.TestStatus object at 0x000002813FEDC7F0>, testName = 'test_validLogin', result = False, resultMessage = 'Login Verification'\n\n    def markFinal(self, testName, result, resultMessage):\n        \"\"\"\n        Mark the final result of the verification point in a test case\n        This needs to be called at least once in a test case\n        This should be final test status of the test case\n        \"\"\"\n        self.setResult(result, resultMessage)\n    \n        if \"FAIL\" in self.resultList:\n            self.log.error(testName +  \" ### TEST FAILED\")\n            self.resultList.clear()\n>           assert True == False\nE           AssertionError\n\n..\\..\\utilities\\teststatus.py:63: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_UnitTestCase__pytest_class_setup",
    "time" : {
      "start" : 1599032658216,
      "stop" : 1599032658216,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "oneTimeSetUp",
    "time" : {
      "start" : 1599032658216,
      "stop" : 1599032678922,
      "duration" : 20706
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "setUp",
    "time" : {
      "start" : 1599032695426,
      "stop" : 1599032695426,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "classSetup",
    "time" : {
      "start" : 1599032695426,
      "stop" : 1599032695426,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "browser",
    "time" : {
      "start" : 1599032658216,
      "stop" : 1599032658216,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError",
    "statusTrace" : "self = <tests.home.test_login.LoginTests testMethod=test_validLogin>\n\n    @pytest.mark.run(order=2)\n    def test_validLogin(self):\n        self.lp.login(\"test@email.com\", \"abcabc\")\n        result1 = self.lp.verifyLoginTitle()\n        self.ts.mark(result1, \"Title Verification\")\n        result2 = self.lp.verifyLoginSuccessful()\n>       self.ts.markFinal(\"test_validLogin\", result2, \"Login Verification\")\n\ntest_login.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utilities.teststatus.TestStatus object at 0x000002813FEDC7F0>, testName = 'test_validLogin', result = False, resultMessage = 'Login Verification'\n\n    def markFinal(self, testName, result, resultMessage):\n        \"\"\"\n        Mark the final result of the verification point in a test case\n        This needs to be called at least once in a test case\n        This should be final test status of the test case\n        \"\"\"\n        self.setResult(result, resultMessage)\n    \n        if \"FAIL\" in self.resultList:\n            self.log.error(testName +  \" ### TEST FAILED\")\n            self.resultList.clear()\n>           assert True == False\nE           AssertionError\n\n..\\..\\utilities\\teststatus.py:63: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "56cea3cd6faff7a9",
      "name" : "log",
      "source" : "56cea3cd6faff7a9.txt",
      "type" : "text/plain",
      "size" : 1908
    }, {
      "uid" : "62dd9d3c9cea565c",
      "name" : "stdout",
      "source" : "62dd9d3c9cea565c.txt",
      "type" : "text/plain",
      "size" : 83
    }, {
      "uid" : "9ee7eb82ba1ddf9e",
      "name" : "stderr",
      "source" : "9ee7eb82ba1ddf9e.txt",
      "type" : "text/plain",
      "size" : 12482
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 3,
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0
  },
  "afterStages" : [ {
    "name" : "_UnitTestCase__pytest_class_setup::0",
    "time" : {
      "start" : 1599032710105,
      "stop" : 1599032710105,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "oneTimeSetUp::0",
    "time" : {
      "start" : 1599032707786,
      "stop" : 1599032710103,
      "duration" : 2317
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "setUp::0",
    "time" : {
      "start" : 1599032707784,
      "stop" : 1599032707784,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "run(order=2)"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('oneTimeSetUp', 'setUp')"
  }, {
    "name" : "parentSuite",
    "value" : "tests.home"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "LoginTests"
  }, {
    "name" : "host",
    "value" : "DESKTOP-1LDCU8B"
  }, {
    "name" : "thread",
    "value" : "11668-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.home.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "9063e34e69b7b663",
      "status" : "failed",
      "statusDetails" : "AssertionError",
      "time" : {
        "start" : 1599032550908,
        "stop" : 1599032553478,
        "duration" : 2570
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "run(order=2)", "@pytest.mark.usefixtures('oneTimeSetUp', 'setUp')" ]
  },
  "source" : "b4694d1406f7151.json",
  "parameterValues" : [ ]
}